[package]
name = "game_engine"
version = "0.1.0"
authors = ["Cameron Eldridge <cameldridge+git@gmail.com>"]

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["image", "mixer"]
